### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by cph101** [hackthegamezJJ/Blooket-Hack-game#4]
Dear hackthegamezJJ,

I hope you have had a good Christmas holiday so far. I would like to help you work on Blooket-Hacking-Page.js, as I have spent lots of time finding ways to make browser extensions (Chrome / Arc / Edge / Safari) for similar hacks, and these are the best I have found. If possible, please could you privately email me at [cph101@icloud.com](mailto:cph101@icloud.com), and we can discuss further.

Best wishes,
cph101

**Comment by cph101** [comment]
PS: I also have multiple other hacks that I made myself, for example to bypass the name length limit.

**Comment by Jude-Gideon** [comment]
He didn't make any of these lmao
